# Generated by Django 5.2.7 on 2025-11-06 11:30

import datetime
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(db_index=True, max_length=255)),
                ('asset_code', models.CharField(max_length=255, unique=True)),
                ('asset_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('manager', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Is this asset currently in service')),
                ('start_date', models.DateField(default=datetime.date.today, help_text='Date the asset was put into service.')),
                ('end_date', models.DateField(blank=True, help_text='Date the asset was decommissioned or inactivated.', null=True)),
                ('custom_data', models.JSONField(blank=True, default=dict, help_text="Flexible field for custom data (e.g., {'warranty_id': 'XYZ-123'})", null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='base.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
